[package]
name = "p2p-internals-git"
version = "0.1.0"
authors = ["Sébastien (AmarOk) Blin <contact@enconn.fr>"]
edition = "2018"

[dependencies]
bichannel = "0.0.4"
git2 = { git = "https://github.com/AmarOk1412/git2-rs" } # Necessary until 0.13.18