[package]
name = "p2p-internals-git"
version = "0.1.0"
authors = ["Sébastien (AmarOk) Blin <contact@enconn.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2="0.13.17"
tempfile = "3"